/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package frame;

import java.awt.Color;
import java.util.ArrayList;
import util.MedicoModel;

/**
 *
 * @author esp02
 */
public class FormularioMedico extends javax.swing.JPanel {
  MedicoModel mm = new MedicoModel();
   private final boolean DEBUG = false;
    /**
     * Creates new form NewJPanel
     * @param option
     */
    public FormularioMedico(int option) {
        initComponents();
           if (option == 1) {
            lbltitulo.setText("MODIFICAR MEDICO");
            cmbID.setVisible(true);
        } else if (option == 2) {
            lbltitulo.setText("AÑADIR MEDICO");
            cmbID.setVisible(false);

        }
    }
      public void setValorCombo(ArrayList<String> l) {

        for (String l1 : l) {
            cmbID.addItem(l1);
        }
         String nombre;
       nombre = mm.getUpdateMedico(cmbID.getSelectedItem().toString());
       String[] campo = nombre.split("\\|");
   if(DEBUG){System.err.println(nombre);}
        txtNombre.setText(campo[0]);  
        txtDirrecion.setText(campo[1]);
        txtTelefono.setText(campo[2]);
        cmPro.setSelectedItem(campo[3]);
        cmbstatus.setSelectedItem(campo[5]);
        txtCuota.setText(campo[4]);

    }

    public String getTextId() {
        return cmbID.getSelectedItem().toString();
    }

      
       public String getTextNombre() {
        return txtNombre.getText();
    }
      
      
    

    public String getTextDirrecion() {
        return txtDirrecion.getText();
    }
 public String getTextTelefono() {
        return txtTelefono.getText();
    }

    public String getTextProvincia() {
        return cmPro.getSelectedItem().toString();
    }

    public String getTextEstatus() {
        return cmbstatus.getSelectedItem().toString();
    }
 
 
 
   public String getTextCuota() {
        return txtCuota.getText();
    }

   


   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lbltitulo = new javax.swing.JLabel();
        cmbID = new javax.swing.JComboBox();
        textPanel = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        txtDirrecion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        cmPro = new javax.swing.JComboBox();
        cmbstatus = new javax.swing.JComboBox();
        txtCuota = new javax.swing.JTextField();
        labelPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbltitulo.setText("Registrar Medico");
        jPanel2.add(lbltitulo);

        cmbID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbIDActionPerformed(evt);
            }
        });
        jPanel2.add(cmbID);

        textPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        textPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 6));

        txtNombre.setPreferredSize(new java.awt.Dimension(150, 26));
        textPanel.add(txtNombre);

        txtDirrecion.setPreferredSize(new java.awt.Dimension(150, 26));
        textPanel.add(txtDirrecion);

        txtTelefono.setText("(555)-555-5555");
        txtTelefono.setPreferredSize(new java.awt.Dimension(150, 26));
        txtTelefono.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTelefonoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTelefonoFocusLost(evt);
            }
        });
        textPanel.add(txtTelefono);

        cmPro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5" }));
        cmPro.setPreferredSize(new java.awt.Dimension(120, 26));
        textPanel.add(cmPro);

        cmbstatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Activo", "Inactivo" }));
        cmbstatus.setPreferredSize(new java.awt.Dimension(120, 26));
        textPanel.add(cmbstatus);

        txtCuota.setPreferredSize(new java.awt.Dimension(150, 26));
        textPanel.add(txtCuota);

        labelPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        labelPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 11));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel1.setText("Nombre");
        labelPanel.add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel2.setText("Direccion");
        labelPanel.add(jLabel2);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel3.setText("Telefono");
        labelPanel.add(jLabel3);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel4.setText("Provincia");
        labelPanel.add(jLabel4);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel5.setText("Estatus");
        labelPanel.add(jLabel5);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel7.setText("Cuota");
        labelPanel.add(jLabel7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbIDActionPerformed

    }//GEN-LAST:event_cmbIDActionPerformed

    private void txtTelefonoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelefonoFocusGained
       if(txtTelefono.getText().equals("(555)-555-5555")){
       txtTelefono.setText("");
           txtTelefono.setForeground(Color.black);
       }
    }//GEN-LAST:event_txtTelefonoFocusGained

    private void txtTelefonoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelefonoFocusLost
        if(txtTelefono.getText().equals("")){
       txtTelefono.setText("(555)-555-5555");
            txtTelefono.setForeground(Color.gray);
       }
    }//GEN-LAST:event_txtTelefonoFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmPro;
    private javax.swing.JComboBox cmbID;
    private javax.swing.JComboBox cmbstatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel labelPanel;
    private javax.swing.JLabel lbltitulo;
    private javax.swing.JPanel textPanel;
    private javax.swing.JTextField txtCuota;
    private javax.swing.JTextField txtDirrecion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
