/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package frame;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.DefaultCellEditor;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.OK_CANCEL_OPTION;
import static javax.swing.JOptionPane.PLAIN_MESSAGE;
import static javax.swing.JOptionPane.showConfirmDialog;
import javax.swing.UIManager;
import util.CheckBoxRenderer;
import util.ProvinciaModel;

/**
 *
 * @author Chyno
 */
public class frmCuotaPagoConsultar extends javax.swing.JFrame {
  JCheckBox check = new JCheckBox();
    ProvinciaModel pm = new ProvinciaModel();
    ArrayList<String> valor = new ArrayList<>();
    /**
     * Creates new form frmCuotaConsultar
     */
    public frmCuotaPagoConsultar() {
        initComponents();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        botomPanel = new javax.swing.JPanel();
        cmbOpcion = new javax.swing.JComboBox();
        txtWhere = new javax.swing.JTextField();
        btnConsultar = new javax.swing.JButton();
        btnPagar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable(){
            @Override
            public boolean isCellEditable(int row, int column) {
                return column == 0 ? true : false;
            }}
            ;
            jPanel3 = new javax.swing.JPanel();
            jMenuBar1 = new javax.swing.JMenuBar();
            jMenu1 = new javax.swing.JMenu();
            mnClose = new javax.swing.JMenuItem();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

            jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

            jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
            jLabel2.setText("BUSQUEDA DE CUOTAS");
            jPanel1.add(jLabel2);

            botomPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

            cmbOpcion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TODO", "ID", "NOMBRE" }));
            cmbOpcion.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    cmbOpcionActionPerformed(evt);
                }
            });
            botomPanel.add(cmbOpcion);

            txtWhere.setForeground(new java.awt.Color(204, 204, 204));
            txtWhere.setToolTipText("");
            txtWhere.setPreferredSize(new java.awt.Dimension(100, 26));
            txtWhere.addFocusListener(new java.awt.event.FocusAdapter() {
                public void focusGained(java.awt.event.FocusEvent evt) {
                    txtWhereFocusGained(evt);
                }
                public void focusLost(java.awt.event.FocusEvent evt) {
                    txtWhereFocusLost(evt);
                }
            });
            botomPanel.add(txtWhere);

            btnConsultar.setText("CONSULTAR");
            btnConsultar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnConsultarActionPerformed(evt);
                }
            });
            botomPanel.add(btnConsultar);

            btnPagar.setText("PAGAR");
            btnPagar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnPagarActionPerformed(evt);
                }
            });
            botomPanel.add(btnPagar);

            btnCerrar.setText("CERRAR");
            btnCerrar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnCerrarActionPerformed(evt);
                }
            });
            botomPanel.add(btnCerrar);

            jScrollPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

            tabla.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
            tabla.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null}
                },
                new String [] {
                    "Title 1", "Title 2", "Title 3", "Title 4"
                }
            ));
            jScrollPane1.setViewportView(tabla);

            javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
            jPanel2.setLayout(jPanel2Layout);
            jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botomPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE))
                    .addContainerGap())
            );
            jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(botomPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                    .addContainerGap())
            );

            jTabbedPane1.addTab("CUOTA", jPanel2);

            javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
            jPanel3.setLayout(jPanel3Layout);
            jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 629, Short.MAX_VALUE)
            );
            jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 359, Short.MAX_VALUE)
            );

            jTabbedPane1.addTab("PAGO", jPanel3);

            jMenu1.setText("File");

            mnClose.setText("Close");
            mnClose.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    mnCloseActionPerformed(evt);
                }
            });
            jMenu1.add(mnClose);

            jMenuBar1.add(jMenu1);

            setJMenuBar(jMenuBar1);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTabbedPane1)
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void mnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_mnCloseActionPerformed

    private void cmbOpcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOpcionActionPerformed
        if (cmbOpcion.getSelectedIndex() == 0) {
            txtWhere.setEnabled(false);
            txtWhere.setText("");
            valor.clear();
        } else {
            txtWhere.setEnabled(true);
            txtWhere.setText("CONDICION");
            txtWhere.setForeground(Color.gray);
            valor.clear();
        }
    }//GEN-LAST:event_cmbOpcionActionPerformed

    private void txtWhereFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtWhereFocusGained
        if ("CONDICION".equals(txtWhere.getText())) {
            txtWhere.setText("");
            txtWhere.setForeground(Color.black);

        }
    }//GEN-LAST:event_txtWhereFocusGained

    private void txtWhereFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtWhereFocusLost
        if ("".equals(txtWhere.getText())) {
            txtWhere.setForeground(Color.gray);
            txtWhere.setText("CONDICION");
        }
    }//GEN-LAST:event_txtWhereFocusLost

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        if (cmbOpcion.getSelectedIndex() == 0) {
            pm.getAllProvincia();
            tabla.setModel(pm.getTableModel());
        } else if (!"CONDICION".equals(txtWhere.getText()) && (cmbOpcion.getSelectedIndex() == 1 || cmbOpcion.getSelectedIndex() == 2)) {
            pm.getProvinciaByCondition(txtWhere.getText(), cmbOpcion.getSelectedIndex());
            tabla.setModel(pm.getTableModel());
            tabla.getColumnModel().getColumn(0).setCellEditor(new DefaultCellEditor(check));
            CheckBoxRenderer checkBoxRenderer = new CheckBoxRenderer();
            tabla.getColumnModel().getColumn(0).setCellRenderer(checkBoxRenderer);
            tabla.updateUI();
        } else {
            JOptionPane.showMessageDialog(new JFrame(), "REVISE LA CONDICION!", "ERROR!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
        FormularioMedico panel = new FormularioMedico(1);
        //  panel.setValorCombo(valor);
        int result = showConfirmDialog(null, panel, "Test",
            OK_CANCEL_OPTION, PLAIN_MESSAGE);
        if (result == JOptionPane.OK_OPTION) {
            System.out.println(panel.getTextNombre());

        } else {
            System.out.println("Cancelled");
        }
    }//GEN-LAST:event_btnPagarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("GTK".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCuotaPagoConsultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCuotaPagoConsultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCuotaPagoConsultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCuotaPagoConsultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new frmCuotaPagoConsultar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botomPanel;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnPagar;
    private javax.swing.JComboBox cmbOpcion;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JMenuItem mnClose;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtWhere;
    // End of variables declaration//GEN-END:variables
}
