/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.DefaultCellEditor;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.OK_CANCEL_OPTION;
import static javax.swing.JOptionPane.PLAIN_MESSAGE;
import static javax.swing.JOptionPane.showConfirmDialog;
import util.CheckBoxRenderer;
import util.ProvinciaModel;

/**
 *
 * @author Chyno
 */
public class frmProvinciaMain extends javax.swing.JFrame {

    JCheckBox check = new JCheckBox();
    ProvinciaModel pm = new ProvinciaModel();
    ArrayList<String> valor = new ArrayList<>();

    /**
     * Creates new form frameProvincia
     */
    public frmProvinciaMain() {

        initComponents();
        this.setLocationRelativeTo(null);
        check.setHorizontalAlignment(JLabel.CENTER);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable(){
            @Override
            public boolean isCellEditable(int row, int column) {
                return column == 0 ? true : false;
            }}
            ;
            botomPanel = new javax.swing.JPanel();
            cmbOpcion = new javax.swing.JComboBox();
            txtWhere = new javax.swing.JTextField();
            btnConsultar = new javax.swing.JButton();
            btnModifica = new javax.swing.JButton();
            jButton3 = new javax.swing.JButton();
            btnCerrar = new javax.swing.JButton();
            jPanel1 = new javax.swing.JPanel();
            jLabel2 = new javax.swing.JLabel();
            jMenuBar1 = new javax.swing.JMenuBar();
            jMenu1 = new javax.swing.JMenu();
            mnClose = new javax.swing.JMenuItem();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            addWindowListener(new java.awt.event.WindowAdapter() {
                public void windowOpened(java.awt.event.WindowEvent evt) {
                    formWindowOpened(evt);
                }
            });

            tabla.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null}
                },
                new String [] {
                    "Title 1", "Title 2", "Title 3", "Title 4"
                }
            ));
            jScrollPane1.setViewportView(tabla);

            botomPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

            cmbOpcion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TODO", "ID", "NOMBRE" }));
            cmbOpcion.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    cmbOpcionActionPerformed(evt);
                }
            });
            botomPanel.add(cmbOpcion);

            txtWhere.setForeground(new java.awt.Color(204, 204, 204));
            txtWhere.setToolTipText("");
            txtWhere.setPreferredSize(new java.awt.Dimension(100, 26));
            txtWhere.addFocusListener(new java.awt.event.FocusAdapter() {
                public void focusGained(java.awt.event.FocusEvent evt) {
                    txtWhereFocusGained(evt);
                }
                public void focusLost(java.awt.event.FocusEvent evt) {
                    txtWhereFocusLost(evt);
                }
            });
            botomPanel.add(txtWhere);

            btnConsultar.setText("CONSULTAR");
            btnConsultar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnConsultarActionPerformed(evt);
                }
            });
            botomPanel.add(btnConsultar);

            btnModifica.setText("MODIFICA");
            btnModifica.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnModificaActionPerformed(evt);
                }
            });
            botomPanel.add(btnModifica);

            jButton3.setText("AGREGAR");
            jButton3.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton3ActionPerformed(evt);
                }
            });
            botomPanel.add(jButton3);

            btnCerrar.setText("CERRAR");
            btnCerrar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnCerrarActionPerformed(evt);
                }
            });
            botomPanel.add(btnCerrar);

            jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

            jLabel2.setText("BUSQUEDA DE PROVINCIA");
            jPanel1.add(jLabel2);

            jMenu1.setText("File");

            mnClose.setText("Close");
            mnClose.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    mnCloseActionPerformed(evt);
                }
            });
            jMenu1.add(mnClose);

            jMenuBar1.add(jMenu1);

            setJMenuBar(jMenuBar1);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(botomPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 852, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                    .addContainerGap())
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(4, 4, 4)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(botomPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void mnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_mnCloseActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        if (cmbOpcion.getSelectedIndex() == 0) {
            pm.getAllProvincia();
            tabla.setModel(pm.getTableModel());
        } else if (!"CONDICION".equals(txtWhere.getText()) && (cmbOpcion.getSelectedIndex() == 1 || cmbOpcion.getSelectedIndex() == 2)) {
            pm.getProvinciaByCondition(txtWhere.getText(), cmbOpcion.getSelectedIndex());
            tabla.setModel(pm.getTableModel());
         
        } else {
            JOptionPane.showMessageDialog(new JFrame(), "REVISE LA CONDICION!", "ERROR!", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_btnConsultarActionPerformed

    private void txtWhereFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtWhereFocusLost
        if ("".equals(txtWhere.getText())) {
            txtWhere.setForeground(Color.gray);
            txtWhere.setText("CONDICION");
        }
    }//GEN-LAST:event_txtWhereFocusLost

    private void cmbOpcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOpcionActionPerformed
        if (cmbOpcion.getSelectedIndex() == 0) {
            txtWhere.setEnabled(false);
            txtWhere.setText("");
            valor.clear();
        } else {
            txtWhere.setEnabled(true);
            txtWhere.setText("CONDICION");
            txtWhere.setForeground(Color.gray);
            valor.clear();
        }

    }//GEN-LAST:event_cmbOpcionActionPerformed

    private void txtWhereFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtWhereFocusGained
        if ("CONDICION".equals(txtWhere.getText())) {
            txtWhere.setText("");
            txtWhere.setForeground(Color.black);

        }
    }//GEN-LAST:event_txtWhereFocusGained

    private void btnModificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificaActionPerformed
        FormularioProvincia panel = new FormularioProvincia(1);
        valor = pm.getValor();
        if (valor.isEmpty() || valor.size()>1) {
            JOptionPane.showMessageDialog(new JFrame(), "ELIJA UN REGISTRO!", "ERROR", JOptionPane.ERROR_MESSAGE            );
        }else {
            panel.setValorCombo(valor);
            int result = showConfirmDialog(null, panel, "MODIFICAR",
                    OK_CANCEL_OPTION, PLAIN_MESSAGE);
            if (result == JOptionPane.OK_OPTION) {
                pm.setUpdateProvincia(panel.getTextNombre(), panel.getTextID());
                btnConsultar.doClick();
            }
        }


    }//GEN-LAST:event_btnModificaActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        cmbOpcion.setSelectedIndex(0);
        btnConsultar.doClick();
    }//GEN-LAST:event_formWindowOpened

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        FormularioProvincia panel = new FormularioProvincia(2);
        //
            int result = showConfirmDialog(null, panel, "AÑADIR",
                    OK_CANCEL_OPTION, PLAIN_MESSAGE);
            if (result == JOptionPane.OK_OPTION) {
             pm.setProvincia(panel.getTextNombre());
                btnConsultar.doClick();
            }
        

    }//GEN-LAST:event_jButton3ActionPerformed

    /*
     * JTable uses this method to determine the default renderer/
     * editor for each cell.  If we didn't implement this method,
     * then the last column would contain text ("true"/"false"),
     * rather than a check box.
     */
    public Class getColumnClass(int c) {
        return tabla.getModel().getValueAt(0, c).getClass();
    }

    /*
     * Don't need to implement this method unless your table's
     * editable.
     */
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new frmProvinciaMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botomPanel;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnModifica;
    private javax.swing.JComboBox cmbOpcion;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem mnClose;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtWhere;
    // End of variables declaration//GEN-END:variables
}
