package d.model.pojos;
// Generated 07/20/2014 08:41:46 PM by Hibernate Tools 3.6.0



/**
 * CuotaxmedicoId generated by hbm2java
 */
public class CuotaxmedicoId  implements java.io.Serializable {


     private int idcuota;
     private int idmedico;

    public CuotaxmedicoId() {
    }

    public CuotaxmedicoId(int idcuota, int idmedico) {
       this.idcuota = idcuota;
       this.idmedico = idmedico;
    }
   
    public int getIdcuota() {
        return this.idcuota;
    }
    
    public void setIdcuota(int idcuota) {
        this.idcuota = idcuota;
    }
    public int getIdmedico() {
        return this.idmedico;
    }
    
    public void setIdmedico(int idmedico) {
        this.idmedico = idmedico;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CuotaxmedicoId) ) return false;
		 CuotaxmedicoId castOther = ( CuotaxmedicoId ) other; 
         
		 return (this.getIdcuota()==castOther.getIdcuota())
 && (this.getIdmedico()==castOther.getIdmedico());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdcuota();
         result = 37 * result + this.getIdmedico();
         return result;
   }   


}


