package d.model.pojos;
// Generated 07/20/2014 08:41:46 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Medico generated by hbm2java
 */
public class Medico  implements java.io.Serializable {


     private int idmedico;
     private String nombre;
     private String direccion;
     private String telefono;
     private Integer idprovincia;
     private Date fechaingreso;
     private String estatus;

    public Medico() {
    }

	
    public Medico(int idmedico) {
        this.idmedico = idmedico;
    }
    public Medico(int idmedico, String nombre, String direccion, String telefono, Integer idprovincia, Date fechaingreso, String estatus) {
       this.idmedico = idmedico;
       this.nombre = nombre;
       this.direccion = direccion;
       this.telefono = telefono;
       this.idprovincia = idprovincia;
       this.fechaingreso = fechaingreso;
       this.estatus = estatus;
    }
   
    public int getIdmedico() {
        return this.idmedico;
    }
    
    public void setIdmedico(int idmedico) {
        this.idmedico = idmedico;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public Integer getIdprovincia() {
        return this.idprovincia;
    }
    
    public void setIdprovincia(Integer idprovincia) {
        this.idprovincia = idprovincia;
    }
    public Date getFechaingreso() {
        return this.fechaingreso;
    }
    
    public void setFechaingreso(Date fechaingreso) {
        this.fechaingreso = fechaingreso;
    }
    public String getEstatus() {
        return this.estatus;
    }
    
    public void setEstatus(String estatus) {
        this.estatus = estatus;
    }




}


