package d.model.pojos;
// Generated 07/20/2014 08:41:46 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Pago generated by hbm2java
 */
public class Pago  implements java.io.Serializable {


     private int idpago;
     private int idcuotames;
     private Integer idmedico;
     private Integer pago;
     private Date fechapago;

    public Pago() {
    }

	
    public Pago(int idpago, int idcuotames) {
        this.idpago = idpago;
        this.idcuotames = idcuotames;
    }
    public Pago(int idpago, int idcuotames, Integer idmedico, Integer pago, Date fechapago) {
       this.idpago = idpago;
       this.idcuotames = idcuotames;
       this.idmedico = idmedico;
       this.pago = pago;
       this.fechapago = fechapago;
    }
   
    public int getIdpago() {
        return this.idpago;
    }
    
    public void setIdpago(int idpago) {
        this.idpago = idpago;
    }
    public int getIdcuotames() {
        return this.idcuotames;
    }
    
    public void setIdcuotames(int idcuotames) {
        this.idcuotames = idcuotames;
    }
    public Integer getIdmedico() {
        return this.idmedico;
    }
    
    public void setIdmedico(Integer idmedico) {
        this.idmedico = idmedico;
    }
    public Integer getPago() {
        return this.pago;
    }
    
    public void setPago(Integer pago) {
        this.pago = pago;
    }
    public Date getFechapago() {
        return this.fechapago;
    }
    
    public void setFechapago(Date fechapago) {
        this.fechapago = fechapago;
    }




}


