package model.pojos;
// Generated 07/24/2014 08:17:34 PM by Hibernate Tools 3.6.0



/**
 * Cuota generated by hbm2java
 */
public class Cuota  implements java.io.Serializable {


     private int idcuotames;
     private Integer idmedico;
     private Integer mes;
     private Integer ano;
     private Integer monto;
     private String estatus;

    public Cuota() {
    }

	
    public Cuota(int idcuotames) {
        this.idcuotames = idcuotames;
    }
    public Cuota(int idcuotames, Integer idmedico, Integer mes, Integer ano, Integer monto, String estatus) {
       this.idcuotames = idcuotames;
       this.idmedico = idmedico;
       this.mes = mes;
       this.ano = ano;
       this.monto = monto;
       this.estatus = estatus;
    }
   
    public int getIdcuotames() {
        return this.idcuotames;
    }
    
    public void setIdcuotames(int idcuotames) {
        this.idcuotames = idcuotames;
    }
    public Integer getIdmedico() {
        return this.idmedico;
    }
    
    public void setIdmedico(Integer idmedico) {
        this.idmedico = idmedico;
    }
    public Integer getMes() {
        return this.mes;
    }
    
    public void setMes(Integer mes) {
        this.mes = mes;
    }
    public Integer getAno() {
        return this.ano;
    }
    
    public void setAno(Integer ano) {
        this.ano = ano;
    }
    public Integer getMonto() {
        return this.monto;
    }
    
    public void setMonto(Integer monto) {
        this.monto = monto;
    }
    public String getEstatus() {
        return this.estatus;
    }
    
    public void setEstatus(String estatus) {
        this.estatus = estatus;
    }




}


